[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mtga_ml"
authors = [{name = "Neal Lawton", email = "nlawton@usc.edu"}]
dynamic = ["version", "description"]
